apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
  namespace: activemq
type: Opaque
stringData:
  credentials.properties: |
    activemq.username=admin
    activemq.password=admin
    guest.username=guest
    guest.password=guest
