apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  namespace: activemq
spec:
  serviceName: activemq
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      serviceAccountName: activemq-sa
      securityContext:                      # 보안 설정
        runAsNonRoot: true        
        runAsUser: 1000           
        runAsGroup: 1000          
        fsGroup: 1000             
        seccompProfile:
          type: RuntimeDefault   
      containers:
      - name: activemq
        image: rmohr/activemq:5.15.9
        securityContext:
          allowPrivilegeEscalation: false   # 권한 상승 금지
          capabilities:                     # 리눅스 커널 권한 제거
            drop:
            - "ALL"
        ports:
        - containerPort: 61616
          name: openwire
        - containerPort: 8161
          name: web
        - containerPort: 61614
          name: websocket
        env:
        - name: ACTIVEMQ_USER
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: ACTIVEMQ_USER
        - name: ACTIVEMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: ACTIVEMQ_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /opt/activemq/conf/activemq.xml
          subPath: activemq.xml
        - name: data
          mountPath: /opt/activemq/data
      volumes:
      - name: config
        configMap:
          name: activemq-config
      - name: data
        persistentVolumeClaim:
          claimName: activemq-data
      
        
    