# admin
# openmaru
apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
  namespace: activemq
type: Opaque
data:
  ACTIVEMQ_USER: YWRtaW4=         
  ACTIVEMQ_PASSWORD: b3Blbm1hcnUK 
  ACTIVEMQ_ADMIN_LOGIN: YWRtaW4=   
  ACTIVEMQ_ADMIN_PASSWORD: b3Blbm1hcnUK
