apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemq-ingress
  namespace: activemq
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: activemq.apps.ocp.beomzh.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: activemq
                port:
                  number: 8161
